# Generated by Django 4.2.2 on 2023-09-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_city_alter_weather_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
    ]
