# Generated by Django 4.2.2 on 2023-09-19 15:00

from django.db import migrations, models
import weather.validators


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_rename_name_city_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100, validators=[weather.validators.validate_city]),
        ),
    ]
