# Generated by Django 5.0 on 2023-12-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_gross_alter_movie_meta_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
