# Generated by Django 4.2.2 on 2023-10-06 14:15

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
