# Generated by Django 4.2.2 on 2023-10-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty', '0003_episode_character_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='url',
            field=models.URLField(),
        ),
    ]
