# Generated by Django 4.2.2 on 2023-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rick_and_morty', '0004_alter_episode_air_date_alter_episode_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='episode',
        ),
        migrations.AddField(
            model_name='episode',
            name='characters',
            field=models.ManyToManyField(related_name='episodes', to='rick_and_morty.character'),
        ),
    ]
